---
sidebar: sidebar 
permalink: task-homepage.html 
keywords: license, licensing, dashboard, capacity license, capacity based license, add license, install license, bluexp, netapp console, cloud volumes ontap license, cloud volumes ontap 
summary: Obtenga una descripción general de todas las suscripciones y licencias de su organización en el panel de descripción general en la Consola. 
---
= Utilice la descripción general del panel de control
:allow-uri-read: 




== Utilice la descripción general del panel de control

[role="lead"]
El panel de control *Overview* en la NetApp Console te ayuda a supervisar los estados de tus licencias y suscripciones para que puedas gestionar los costos y mantener el servicio cuando las suscripciones lleguen a las fechas de vencimiento o a los límites de capacidad.

Puedes ver información específica sobre licencias y suscripciones de cada uno de tus servicios de datos (incluido Cloud Volumes ONTAP).

El panel de Licenses and subscriptions te avisa de los próximos límites de capacidad o vencimientos, para que tomes las medidas necesarias.



=== Ver detalles sobre un servicio de datos específico

El panel *Overview* ofrece información detallada sobre los siguientes servicios:

* Copia de seguridad y recuperación
* Nivelación de la nube
* Cloud Volumes ONTAP
* Recuperación ante desastres
* Resiliencia frente al ransomware


Por ejemplo, los administradores encargados de gestionar los recursos de Cloud Volumes ONTAP pueden ver la capacidad actual de cada licencia o suscripción, lo que les brinda una visión enfocada de los recursos dentro de su ámbito de competencia.


NOTE: Si bien puedes actualizar y eliminar licencias desde el panel de control, no puedes agregar una nueva licencia o suscripción.

link:task-manage-data-services-licenses.html["Obtenga más información sobre la gestión de licencias"]. link:task-manage-subscriptions.html["Obtenga más información sobre la gestión de suscripciones"].

.Pasos
. Desde el menú de la NetApp Console , seleccione *Administración > Licenses and subscriptions*.
. Seleccione *Descripción general*.
. Seleccione *Ver* para el servicio de datos correspondiente (incluido Cloud Volumes ONTAP) para ver detalles y administrar licencias y suscripciones.
+
Cada mosaico proporciona una descripción gráfica de la capacidad.  Puede ver la página de detalles para ver y administrar los métodos de pago para esa capacidad.

. Seleccione la pestaña *Licencias* o *Suscripciones*.
. Filtre la tabla seleccionando un filtro de columna y un valor para filtrar.  Por ejemplo, en la pestaña *Suscripciones*, puede filtrar la columna Tipo por Contrato anual o Suscripción.
. Personaliza las columnas que se muestran en la tabla.  Puede agregar y eliminar columnas de la tabla seleccionando el ícono *Columna* para indicar qué columnas desea mostrar u ocultar.
. Expanda cualquier fila para ver detalles de lo que incluye la suscripción o licencia, la capacidad adquirida y los términos.
. Utilice el menú de acciones para administrar una licencia o suscripción específica, como actualizar una licencia o asociar una suscripción con una organización diferente.
+
No puedes añadir nuevas licencias o suscripciones desde la página *Vista general* de un servicio específico. Solo puedes añadir licencias desde la pestaña *Licencias directas* o suscripciones desde la pestaña *Suscripciones a Marketplace*.

+
link:task-manage-data-services-licenses.html["Obtenga más información sobre la gestión de licencias."] link:task-manage-subscriptions.html["Obtenga más información sobre cómo administrar suscripciones."]





=== Resolver problemas de licencia o suscripción

En el panel de información general, puedes ver los problemas de licencias y suscripciones que deben resolverse. Los problemas incluyen licencias y suscripciones que están por caducar o que están llegando al límite de su capacidad.

. Desde el menú de la NetApp Console , seleccione *Administración > Licenses and subscriptions*.
. Seleccione *Descripción general*.
. En el mosaico *Requiere acción*, selecciona *Resolver* para ver los problemas que deben ajustarse. Si no aparece *Resolver*, no hay problemas que requieran acción.
. Desde la página *Requiere acción*, seleccione la pestaña *Licencias* o la pestaña *Suscripciones*.
. Utilice el menú de acciones para resolver el problema.
+
** link:task-manage-data-services-licenses.html["Obtenga más información sobre la gestión de licencias"].
** link:task-manage-subscriptions.html["Obtenga más información sobre la gestión de suscripciones"].



