---
sidebar: sidebar 
permalink: task-manage-private-aws.html 
keywords: activate, license, licensing, install, request capacity, link subscription, keystone flex, bluexp, netapp console, marketplace, aws 
summary: Acepta una oferta privada de Marketplace para la NetApp Console en el AWS Marketplace Portal y configura las credenciales de AWS en la Console. 
---
= Acepte y configure una oferta privada de AWS Marketplace para la NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Acepta una oferta privada de Marketplace para la NetApp Console en el AWS Marketplace Portal y configura las credenciales de AWS en la Console.

.Antes de empezar
* Trabaje con el equipo de ventas de NetApp para crear una oferta privada y obtener el enlace de activación.
* Asegúrese de tener los permisos necesarios de AWS Marketplace:
+
** link:https://docs.aws.amazon.com/marketplace/latest/buyerguide/buyer-private-offers-subscribing.html["Visualización y suscripción a una oferta privada"]
** link:https://docs.aws.amazon.com/marketplace/latest/buyerguide/buyer-iam-users-groups-policies.html["Validación de permisos del comprador"]






== Acepta la oferta privada en el portal de AWS Marketplace

Es necesario completar la asignación de suscripción en la Consola para activar la compra y aplicar el precio con descuento.


NOTE: Debes completar todos los pasos para activar tu oferta privada. Omitir pasos puede causar errores de facturación. Aceptar y activar la oferta varias veces puede resultar en un doble cobro.

.Pasos
. Selecciona el enlace de activación de la oferta privada de tu equipo de ventas de NetApp.
+
El enlace debe tener un aspecto similar al siguiente: `https://aws.amazon.com/marketplace/saas/ordering?productId=aaa&offerId=offer-aaa`

+
Si no recibiste el enlace, consulta las ofertas privadas en la consola de AWS Marketplace. Se requieren los siguientes permisos:

+
** Uso de políticas administradas de AWS: *AWSMarketplaceRead-only*, *AWSMarketplaceManageSubscriptions* o *AWSMarketplaceFullAccess*
** Uso de políticas de IAM personalizadas: `aws-marketplace:ListPrivateListings` y `aws-marketplace:ViewSubscriptions`


. Se le redirige a AWS Marketplace para ver la oferta privada.
+

NOTE: Las ofertas privadas se crean sobre listados públicos. Utilice el menú desplegable *Selección de oferta* para alternar entre ofertas públicas y privadas.

. Revise los detalles de la oferta privada y confirme que coincidan con su acuerdo. Si son incorrectos no los acepte. Comuníquese con su equipo de cuentas de NetApp .
+
[NOTE]
====
Existen dos tipos de ofertas privadas:

** *Uso bajo demanda*
+
*** Información de precios
*** Términos legales


** *Contrato*
+
*** Duración y fechas
*** Configuración de renovación
*** Opciones de contrato
*** Precio total del contrato




Para ofertas de contrato, ingrese el número de unidades acordadas. Para Cloud Volumes ONTAP, asegúrese de seleccionar la licencia correcta antes de suscribirse.

====
. Para aceptar la oferta privada, haga lo siguiente:
+
.. Para un uso a la carta, selecciona *Suscribirse*.
.. Para las ofertas de contrato, introduce el número de unidades de cada servicio y selecciona *Crear contrato*.


. Después de la aceptación, un banner confirma la suscripción y proporciona instrucciones para el registro.
. Selecciona *Set up your account*. Esto te redirige a la NetApp Console para configurar la suscripción.
+
[NOTE]
====
Si aceptaste la oferta pero no completaste el registro, vuelve a la página del producto. Para los listados de contratos, selecciona *Ver opciones de compra* para mostrar la oferta y luego selecciona *Configurar tu cuenta*.

====
. Sign in en  https://console.netapp.com[].
. Después de iniciar sesión, navegue a https://console.netapp.com/licenses/overview[] . Se le solicitará que:
+
.. Introduzca un *Nombre para mostrar* para la suscripción de Marketplace.
.. Selecciona la Console *Organization* con acceso a la suscripción.
.. [Opcional] Activa *Reemplazar suscripción existente* para sobrescribir una suscripción existente para una organización.
+
[NOTE]
====
*** El reemplazo se aplica solo a una cuenta de consola.
*** Para asociar varias cuentas con la misma suscripción, configure cuentas adicionales manualmente.
*** Si las credenciales nunca se asociaron a una suscripción, asócielas manualmente como se describe en la siguiente sección.


====


. Selecciona **Associate**.
. Rellena el formulario para asociar la suscripción con tu organización de NetApp Console. Selecciona **Associate**.
. Después de asociar la suscripción, selecciona la pestaña **Preferencias de facturación**.
. Revisa las opciones de suscripción del mercado.
. Seleccione la suscripción al mercado que desea facturar.  Esto solo se aplica cuando hay más de una opción.
. Seleccione **Guardar cambios**.
. Repite estos pasos según sea necesario si hay varias suscripciones en varios proveedores de nube.


Para obtener más información sobre las suscripciones al mercado y la facturación directa de licencias, consulte la link:https://docs.netapp.com/us-en/console-licenses-subscriptions/concept-billing-preferences.html["Documentación de preferencias de facturación"].
